# Generated by Django 5.2.16 on 2026-07-10 06:19

import apps.screener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to=apps.screener.models.screenshot_upload_path),
        ),
    ]